language: rust
rust:
  - 1.19.0
install:
  # Install samtools
  - wget https://github.com/samtools/samtools/releases/download/1.6/samtools-1.6.tar.bz2
  - tar -jxf samtools-1.6.tar.bz2
  - pushd samtools-1.6 && ./configure --prefix=/usr && make && sudo make install && popd
script:
  - make rust-test
